### ISSUE TITLE
Sending figures to vendor

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#10]
This issue is possibly out-of-scope for this parsing library, but I will start with a brief description of the situation to consider here.

If a decision letter or author response has an image / figure, I expect they will be included as part of the input zip file, which can be added to an S3 bucket, triggering a procedure. When there is a placeholder in the `.docx` referring to a figure, in the output XML we might include something like this:

`<graphic mime-subtype="jpeg" mimetype="image" xlink:href="elife-39122-resp-fig2"/>`

There might be a file named `elife-39122-resp-fig2.jpg` or `elife-39122-resp-fig2.png` or `elife-39122-resp-fig2.tif`, depending on what was supplied in the zip file.

**Finally the question:** Will we be sending these image files to the vendor, and if so, are they via an API endpoint, or by file transfer (bucket, or FTP, for example)?

* [x] Send by API endpoint, bucket, or by FTP? Answer (right now): FTP
* [x] ~~Rename images files to a standard naming format.~~ Answer: Will do later as a possible enhancement in new issue https://github.com/elifesciences/decision-letter-parser/issues/65
* [x] Include references to the image files into the JATS XML generated
* [x] ~~As part of a processing workflow, do we want or need to convert image files to `.tif` format or other format?~~ Answer: Out of scope to this library project at this time

**Comment by gnott** [comment]
If we follow a pattern similar to how digests are processed, we might be able to upload the images to a bucket, and then we can include links to those images to the vendor. That would avoid having to send binary content to an API endpoint, but the vendor may have a preference which is better for them. It may be a point of discussion to start soon.

**Comment by Melissa37** [comment]
I have asked this question of Exeter: https://gitlab.com/ExeterPremedia/Customers/eLife-1.5/issues/285

I have asked them to respond to questions in a timely manner so we can make decisions as we go.

**Comment by gnott** [comment]
Many of the sample decision letter files I have for reference, they have a `.jpg` image file for the figures. I wonder if that format is fine to deliver to the typesetters, or would it be better to try and convert them to `.tif` files? @Melissa37 ?

**Comment by Melissa37** [comment]
>Many of the sample decision letter files I have for reference, they have a .jpg image file for the figures. I wonder if that format is fine to deliver to the typesetters, or would it be better to try and convert them to .tif files? @Melissa37 ?

Looking at the Google drive they are stored in when eLife Editorial create these images, they mainly seem to be .png files, which we upload as-is to Exeter's system. We could find out from Exeter what they convert them to internally (they probably store them as .tiff and then eLife does the conversion to .jpeg in Continuum). I don't think we need to worry about this process at our end for now, until we are loading direct to Libero Editor (Texture).

I think whatever eLife Editorial upload in the zip file is what Exeter can handle and we don't need to process - they do it at their end.

**Comment by gnott** [comment]
I think the result of our call today is we would supply the image files we have -- probably `.jpg`, or could be `.png` or `.tif` -- that was in the zip file deposited to the bucket. But, I think @Melissa37 you considered to clarify whether it would be better if eLife did some image format conversion before sending them to the typesetter.

**Comment by Melissa37** [comment]
Thanks @gnott I have asked Exeter on https://gitlab.com/ExeterPremedia/Customers/eLife-1.5/issues/285

**Comment by Melissa37** [comment]
@gnott I am assigning this back to you as I understand we have the answer from Exeter?

>For AR/DL figure, there is no restriction at our end, it can be any figure type. I have referred your sample and it is in Tiff that would be fine for us.

**Comment by gnott** [comment]
On reviewing this issue

- Resizing images is out-of-scope, and we're not implementing it yet
- Renaming of files I pushed to a new issue specific to it. We are not renaming files at this time

The `assets` in a `.zip` file are identified by this library when it unzips the `.zip`, and those assets -- in an operational workflow -- will be copied to a folder in an S3 bucket, as the way to send figures to the vendor.
