### ISSUE TITLE
Test parsing strike / strike-through

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#13]
After looking at the contents of existing `<sub-article>` tags, there are some articles with a `<strike>` tag (listed below).

Task here is to test strike-through style in a `.docx` file to see what sort of JATS output pandoc produces. Alternatively, search out the `.docx` file for one of these previous articles (if available) to see what was inside.

@Melissa37 an FYI, unless we do not want to support `<strike>` tag when converting from `.docx` to decision letter JATS.

Example articles:

```
10.7554/eLife.34497, strike
10.7554/eLife.34497, strike
10.7554/eLife.21476, strike
10.7554/eLife.21476, strike
10.7554/eLife.21476, strike
10.7554/eLife.25755, strike
10.7554/eLife.01621, strike
```

**Comment by Melissa37** [comment]
@gnott 
This is a problem with processing. I assume the editorial process has left these items in and they have been processed by Exeter's automated conversion system (as you would expect) and we/authors have not spotted them in proofing.

Word file screenshot:
![Syed 34497docx](https://user-images.githubusercontent.com/6051876/62522376-79e91880-b829-11e9-8c1a-1812942d1c37.png)

HTML view screenshot:
![Screenshot 2019-08-06 at 09 06 59](https://user-images.githubusercontent.com/6051876/62522420-91c09c80-b829-11e9-90c0-5f28676a06c4.png)

I guess the options are:

- Editorial manually stop allowing strike through to come through to production

- Above + you delete anything converted to `<strike>` from the XML before sending to Exeter

I'll discuss with Editorial

**Comment by Melissa37** [comment]
>Would it be OK if we asked Graham to ignore this content and not process it?

From editorial: Yes, I think so. I assume these are leftover formatting that authors have included in their response docs and we've missed removing them.

**Comment by gnott** [comment]
Removing `<strike>` tags from cleanly parsed content in commit https://github.com/elifesciences/decision-letter-parser/commit/4367ac12f0e093ca02d0a3ac256f37db63c91495
