### ISSUE TITLE
Test parsing table-wrap from .docx file

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#14]
After looking at the contents of existing `<sub-article>` tags, there are some articles with a `<table-wrap>` tag (listed below).

Task here is to test parsing a table from a `.docx` file to see what sort of JATS output pandoc produces. Alternatively, search out the `.docx` file for one of these previous articles (if available) to see what was inside.

@Melissa37 an FYI - I assume we would like to parse tables from a `.docx` file (if we can) to decision letter JATS.

Example articles:

```
10.7554/eLife.00051, table-wrap
10.7554/eLife.00523, table-wrap
10.7554/eLife.00675, table-wrap
10.7554/eLife.01440, table-wrap
10.7554/eLife.01998, table-wrap
10.7554/eLife.02077, table-wrap
10.7554/eLife.02077, table-wrap
10.7554/eLife.02504, table-wrap
10.7554/eLife.02557, table-wrap
10.7554/eLife.02653, table-wrap
10.7554/eLife.02725, table-wrap
10.7554/eLife.02777, table-wrap
10.7554/eLife.02777, table-wrap
10.7554/eLife.02999, table-wrap
10.7554/eLife.03032, table-wrap
10.7554/eLife.03397, table-wrap
10.7554/eLife.03925, table-wrap
10.7554/eLife.03925, table-wrap
10.7554/eLife.03925, table-wrap
10.7554/eLife.04034, table-wrap
10.7554/eLife.04070, table-wrap
10.7554/eLife.04106, table-wrap
10.7554/eLife.04106, table-wrap
10.7554/eLife.05198, table-wrap
10.7554/eLife.06462, table-wrap
10.7554/eLife.06513, table-wrap
10.7554/eLife.06513, table-wrap
10.7554/eLife.06664, table-wrap
10.7554/eLife.06990, table-wrap
10.7554/eLife.07197, table-wrap
10.7554/eLife.07197, table-wrap
10.7554/eLife.07624, table-wrap
10.7554/eLife.08440, table-wrap
10.7554/eLife.08440, table-wrap
10.7554/eLife.08500, table-wrap
10.7554/eLife.08504, table-wrap
10.7554/eLife.08504, table-wrap
10.7554/eLife.09391, table-wrap
10.7554/eLife.09668, table-wrap
10.7554/eLife.09684, table-wrap
10.7554/eLife.10181, table-wrap
10.7554/eLife.10181, table-wrap
10.7554/eLife.10250, table-wrap
10.7554/eLife.10566, table-wrap
10.7554/eLife.11305, table-wrap
10.7554/eLife.11466, table-wrap
10.7554/eLife.11614, table-wrap
10.7554/eLife.11721, table-wrap
10.7554/eLife.12215, table-wrap
10.7554/eLife.12215, table-wrap
10.7554/eLife.12509, table-wrap
10.7554/eLife.12509, table-wrap
10.7554/eLife.13662, table-wrap
10.7554/eLife.14155, table-wrap
10.7554/eLife.14203, table-wrap
10.7554/eLife.14334, table-wrap
10.7554/eLife.14698, table-wrap
10.7554/eLife.14709, table-wrap
10.7554/eLife.15159, table-wrap
10.7554/eLife.16381, table-wrap
10.7554/eLife.16644, table-wrap
10.7554/eLife.17462, table-wrap
10.7554/eLife.17929, table-wrap
10.7554/eLife.19130, table-wrap
10.7554/eLife.19130, table-wrap
10.7554/eLife.20470, table-wrap
10.7554/eLife.20697, table-wrap
10.7554/eLife.21184, table-wrap
10.7554/eLife.21199, table-wrap
10.7554/eLife.21476, table-wrap
10.7554/eLife.21778, table-wrap
10.7554/eLife.21937, table-wrap
10.7554/eLife.22169, table-wrap
10.7554/eLife.22169, table-wrap
10.7554/eLife.22567, table-wrap
10.7554/eLife.22767, table-wrap
10.7554/eLife.22939, table-wrap
10.7554/eLife.22939, table-wrap
10.7554/eLife.22962, table-wrap
10.7554/eLife.22962, table-wrap
10.7554/eLife.23190, table-wrap
10.7554/eLife.23355, table-wrap
10.7554/eLife.23355, table-wrap
10.7554/eLife.23471, table-wrap
10.7554/eLife.23471, table-wrap
10.7554/eLife.23471, table-wrap
10.7554/eLife.23471, table-wrap
10.7554/eLife.23629, table-wrap
10.7554/eLife.23670, table-wrap
10.7554/eLife.23670, table-wrap
10.7554/eLife.23955, table-wrap
10.7554/eLife.23990, table-wrap
10.7554/eLife.24001, table-wrap
10.7554/eLife.24260, table-wrap
10.7554/eLife.24901, table-wrap
10.7554/eLife.25884, table-wrap
10.7554/eLife.25887, table-wrap
10.7554/eLife.26231, table-wrap
10.7554/eLife.26231, table-wrap
10.7554/eLife.26231, table-wrap
10.7554/eLife.26268, table-wrap
10.7554/eLife.26377, table-wrap
10.7554/eLife.26580, table-wrap
10.7554/eLife.26693, table-wrap
10.7554/eLife.26851, table-wrap
10.7554/eLife.27014, table-wrap
10.7554/eLife.27049, table-wrap
10.7554/eLife.27602, table-wrap
10.7554/eLife.28132, table-wrap
10.7554/eLife.28366, table-wrap
10.7554/eLife.28440, table-wrap
10.7554/eLife.28673, table-wrap
10.7554/eLife.28751, table-wrap
10.7554/eLife.28927, table-wrap
10.7554/eLife.28927, table-wrap
10.7554/eLife.28927, table-wrap
10.7554/eLife.28948, table-wrap
10.7554/eLife.29213, table-wrap
10.7554/eLife.29312, table-wrap
10.7554/eLife.29312, table-wrap
10.7554/eLife.29312, table-wrap
10.7554/eLife.30120, table-wrap
10.7554/eLife.30433, table-wrap
10.7554/eLife.30860, table-wrap
10.7554/eLife.30918, table-wrap
10.7554/eLife.31185, table-wrap
10.7554/eLife.31185, table-wrap
10.7554/eLife.31543, table-wrap
10.7554/eLife.31549, table-wrap
10.7554/eLife.31755, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31826, table-wrap
10.7554/eLife.31949, table-wrap
10.7554/eLife.32057, table-wrap
10.7554/eLife.32057, table-wrap
10.7554/eLife.32143, table-wrap
10.7554/eLife.32177, table-wrap
10.7554/eLife.32451, table-wrap
10.7554/eLife.32640, table-wrap
10.7554/eLife.32671, table-wrap
10.7554/eLife.32740, table-wrap
10.7554/eLife.32740, table-wrap
10.7554/eLife.32976, table-wrap
10.7554/eLife.33361, table-wrap
10.7554/eLife.33361, table-wrap
10.7554/eLife.33468, table-wrap
10.7554/eLife.34114, table-wrap
10.7554/eLife.34286, table-wrap
10.7554/eLife.34286, table-wrap
10.7554/eLife.34292, table-wrap
10.7554/eLife.34354, table-wrap
10.7554/eLife.34955, table-wrap
10.7554/eLife.34976, table-wrap
10.7554/eLife.35453, table-wrap
10.7554/eLife.35453, table-wrap
10.7554/eLife.35500, table-wrap
10.7554/eLife.35684, table-wrap
10.7554/eLife.35684, table-wrap
10.7554/eLife.35684, table-wrap
10.7554/eLife.35684, table-wrap
10.7554/eLife.35854, table-wrap
10.7554/eLife.35989, table-wrap
10.7554/eLife.35989, table-wrap
10.7554/eLife.36173, table-wrap
10.7554/eLife.36173, table-wrap
10.7554/eLife.36468, table-wrap
10.7554/eLife.36769, table-wrap
10.7554/eLife.36842, table-wrap
10.7554/eLife.36842, table-wrap
10.7554/eLife.36842, table-wrap
10.7554/eLife.36998, table-wrap
10.7554/eLife.38314, table-wrap
10.7554/eLife.38822, table-wrap
10.7554/eLife.38822, table-wrap
10.7554/eLife.38822, table-wrap
10.7554/eLife.38889, table-wrap
10.7554/eLife.40765, table-wrap
10.7554/eLife.41115, table-wrap
10.7554/eLife.41159, table-wrap
10.7554/eLife.41362, table-wrap
10.7554/eLife.41770, table-wrap
10.7554/eLife.42223, table-wrap
10.7554/eLife.42271, table-wrap
10.7554/eLife.42271, table-wrap
10.7554/eLife.42274, table-wrap
10.7554/eLife.42299, table-wrap
10.7554/eLife.42299, table-wrap
10.7554/eLife.43333, table-wrap
10.7554/eLife.43400, table-wrap
10.7554/eLife.43410, table-wrap
10.7554/eLife.43732, table-wrap
10.7554/eLife.43732, table-wrap
10.7554/eLife.44179, table-wrap
10.7554/eLife.45068, table-wrap
```

**Comment by Melissa37** [comment]
[Wohrle 43333 es kriya.docx](https://github.com/elifesciences/decision-letter-parser/files/3471090/Wohrle.43333.es.kriya.docx)

Here is one example, and I have shared the eLife googledrive with you that contains all the Word files of decision letters and author responses.

Thanks!

**Comment by gnott** [comment]
I am using a snippet from article `35684` as a first test case. The test itself I think works, but there will probably be further formatting to get the best final output. I'll create a new issue for formatting table JATS XML.

**Comment by gnott** [comment]
I may also include an example from article `43333`, because that table has some cells with `rowspan="7"` in the final JATS XML, and the first example does not have any merged cells in the table.

**Comment by gnott** [comment]
It looks like when testing the table in article `43333`, the merged cells in the first column, the value in the cell is `CRC`, which spans seven table rows, when pandoc converts it to JATS output, the result is a blank `<td></td>` on each row, and it does not automatically interpret this as `<td rowspan="7">` which was used in the final JATS for article `43333`.

@Melissa37, do you have any thoughts on whether the merged cells from an original `.docx` file is important to (try and) preserve the merged cells, or do you think for supplying to typesetters, have seven blank `<td></td>` tags will indicate how the table should be formatted?

**Comment by gnott** [comment]
Included below is a visual of the first column containing `CRC` that has merged cells in the `.docx` table:

![image](https://user-images.githubusercontent.com/1779115/64136470-98015480-cda6-11e9-9351-f76b2edd9bb9.png)

**Comment by gnott** [comment]
Article `43410` has examples of `<td colspan="8">` and `<td colspan="3">` in the final JATS, if we want to account for horizontally merged cells.

**Comment by gnott** [comment]
Article `42299` `Author response table 2` has both `colspan` and `rowspan` in the same table.

**Comment by Melissa37** [comment]
@gnott 

>@Melissa37, do you have any thoughts on whether the merged cells from an original .docx file is important to (try and) preserve the merged cells, or do you think for supplying to typesetters, have seven blank <td></td> tags will indicate how the table should be formatted?

I think the problem is that if the cells are no longer merged, the text CRC will appear in row 2 and then all the following column 1 rows will be blank for that row and it makes the reader assume the text should be CRC there too - which I think could be misleading.

I am @JGilbert-eLife to see whether he has an opinion, but I think this won't work. Do you know how hard it would be to "fix" this?

**Comment by JGilbert-eLife** [comment]
I'd say in most cases, retaining merged cells and assorted table alignment is important. Not retaining it will affect the interpretation of the data, and I don't think we can mandate that authors avoid using merged cells.

**Comment by gnott** [comment]
At this time, it looks like `pandoc` does not support parsing and retaining the merged cells from tables https://github.com/jgm/pandoc/issues/1024.

I think it is worth looking at other methods to post-process the JATS table to add back the `colspan` and `rowspan`. First to see if someone else has tried to tackle it in a library like `htmltidy` or custom solution. Second, to see if the logic to build a table cleaner routine ourselves for limited situations.

**Comment by gnott** [comment]
I tried parsing with the `python-docx` library that we use for parsing digests. The result is not too much better, where the value of the cell that is merged across columns ends up in each cell, therefore there are three cells with the same value, vs. pandoc output has one cell with the value and two blank cells in the output. Adding `python-docx` to extract extra table data will probably not help with merged table cells.

**Comment by gnott** [comment]
Regarding the alignment of table cell contents, I see the pandoc JATS output as omitting those details so far. In some quick tests, parsing a table from a `.docx` with output to MarkDown or Text format I do not think include the cell alignment either, even though pandoc seems to support alignment in those formats. I think it may not be getting the alignment data from the `.docx` itself.

The `python-docx` library may be something to mix in, which seems to parse the cell's paragraph alignment, and the cell vertical alignment. This might act as a guide to the alignment to add back to the pandoc produced JATS table cells.

**Comment by gnott** [comment]
Thanks for the input on the questions discovered during initial testing. The next steps are outlined in issue https://github.com/elifesciences/decision-letter-parser/issues/17, which hopefully reflects all we want to do so far. I will close this `"test parsing"` issue and continue on the subsequent issue.
