### ISSUE TITLE
permissions tag parsing

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#15]
After looking at the contents of existing `<sub-article>` tags, I found only one article with a `<permissions>` tag:

```
10.7554/eLife.36073, permissions
```

It is in the file `elife-36073-v3.xml`.

@Melissa37 - is it safe to assume we can ignore specifying figure permissions in a decision letter `.docx` file for parsing, and it can be added later in the production process? Or, would you like to define a method of specifying a figure license into a `.docx` file so it can be parsed automatically?

**Comment by Melissa37** [comment]
[Oegema 36073 edit 2.docx](https://github.com/elifesciences/decision-letter-parser/files/3471102/Oegema.36073.edit.2.docx)

>Is it safe to assume we can ignore specifying figure permissions in a decision letter .docx file for parsing, and it can be added later in the production process? 

@gnott Yes I think it is. Editorial alerted us to this when creating it and we separately emailed Exeter to ask them to add it - their process did not pick it up and convert the tagging automatically. I suspect Kriya would struggle to ingest the correct tagging and have to do some behind the scenes work to get it in.
Thanks!

**Comment by gnott** [comment]
Cool - thanks! I will close this issue, with no action required to parse permissions from a `.docx` file.
