### ISSUE TITLE
Test parsing lists from docx files

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#16]
After looking at the contents of existing `<sub-article>` tags, there are some articles with a `<list>` tag (listed below).

Task here is to test parsing a list from a `.docx` file to see what sort of JATS output pandoc produces. Alternatively, search out the `.docx` file for one of these previous articles (if available) to see what was inside.

@Melissa37 an FYI, I assume we would like to automatically parse lists from `.docx` files into decision letter JATS output (if it is not too much effort).

Example articles:

```

10.7554/eLife.00031, list
--
10.7554/eLife.00031, list
10.7554/eLife.00031, list
10.7554/eLife.01438, list
10.7554/eLife.01438, list
10.7554/eLife.01695, list
10.7554/eLife.01695, list
10.7554/eLife.03970, list
10.7554/eLife.13388, list
10.7554/eLife.13571, list
10.7554/eLife.14093, list
10.7554/eLife.14093, list
10.7554/eLife.14321, list
10.7554/eLife.15278, list
10.7554/eLife.16644, list
10.7554/eLife.16764, list
10.7554/eLife.18675, list
10.7554/eLife.20818, list
10.7554/eLife.23326, list
10.7554/eLife.23743, list
10.7554/eLife.23743, list
10.7554/eLife.24231, list
10.7554/eLife.25174, list
10.7554/eLife.25776, list
10.7554/eLife.25776, list
10.7554/eLife.25776, list
10.7554/eLife.26111, list
10.7554/eLife.27798, list
10.7554/eLife.27798, list
10.7554/eLife.27798, list
10.7554/eLife.27798, list
10.7554/eLife.27798, list
10.7554/eLife.27798, list
10.7554/eLife.27798, list
10.7554/eLife.29089, list
10.7554/eLife.34353, list
10.7554/eLife.34353, list
10.7554/eLife.34353, list
10.7554/eLife.34353, list


```

**Comment by Melissa37** [comment]
>I assume we would like to automatically parse lists from .docx files into decision letter JATS output (if it is not too much effort).

Yes please! I've loaded 2 sample docs here and I think the rest would. be in the google folder I shared with you

[Igaev 34353.docx](https://github.com/elifesciences/decision-letter-parser/files/3471163/Igaev.34353.docx)

For this example (34353), there were no bullets in the original Word file, but they've been added during the production process - I am not convinced they are all totally necessary! 

[Zaaijer 27798.docx](https://github.com/elifesciences/decision-letter-parser/files/3471197/Zaaijer.27798.docx)

This second one (27798) is interesting as it has numbered and bulleted lists and something has gone pretty wrong during the conversion process! The numbered lists have repeats of numbers and so bit nonsensical now!
@eLifeProduction I think we might want to do a new version of 27798 to correct the author response numbering in the lists.

**Comment by gnott** [comment]
Yes, I'm using article `27798` as the basis of the first list test fixture file, and I see how the first numeric list that has an indented list was converted to paragraphs in the final JATS XML. I will include the lists from the `.docx` file in the test fixture so it can serve as an example to demonstrate the pandoc JATS output, and to see how it may retain the list structure.

**Comment by gnott** [comment]
An observation unrelated to list structures in the `.docx` file for article `27798`, the `Decision letter` and `Author response` paragraphs are not bold, which currently the parser would not recognise as section headings. I imagine in future the emphasis on these two will always be bold in order to be accepted for processing into JATS correctly (although it may be possible to also allow non-bold font, as long as the text on the line is exactly those terms and nothing more).

**Comment by gnott** [comment]
Something I've not seen yet in the pandoc JATS output is the contents of the first list in the article `27798` author response has a `<disp-quote>` around each list item, e.g.

```
<list list-type="order">
  <list-item>
    <disp-quote>
      <p>Contamination and rapid identification: cell line ...
```

I cannot find formatting or properties in the `.docx` file indicating these would be quotations, so it might be something the pandoc parser is doing related to the ordered list.

For eLife, we'll want to strip out the `<disp-quote>` tags here, because `<disp-quote>` will be used differently for italic paragraphs to denote actual quotations.

**Comment by gnott** [comment]
Article `25776` final JATS has a `<list list-type="order">` too, and that `.docx` could additionally be tested to see if the `<disp-quote>` tag comes from that `.docx` too.

**Comment by gnott** [comment]
I reviewed all the examples available of lists for parsing, and I think the testing phase is done. Further XML cleanup will progress in issue https://github.com/elifesciences/decision-letter-parser/issues/18.
