### ISSUE TITLE
Specify the decision letter and author response DOI

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#29]
## Problem / Motivation

- WHO wants this? Typesetters and Production
- WHEN and WHERE do they want it? When JATS XML is generated as a product of when a zip file containing a `.docx` file dropped into an S3 bucket
- WHAT do they want? Add the DOI for both the decision letter and author response into the JATS XML generated as an `<article-id>` tag
- WHY do they want this? The DOI is the identifier for the particular sub article and will probably serve as a marker for the Typesetters

## Proposed solution

- Harvest the DOI or article ID from the zip file
- If it is just an article ID, have a configuration file where a DOI format can be specified, e.g. if the article ID is `666` for eLife it will result in a DOI value of `10.7554/eLife.00666.DL` for the decision letter and `10.7554/eLife.00666.AR` for the author response

## Clarification needed and assumptions

- Question is: there are a few ways the article ID or DOI could be specified, including: 
  - we establish a decision letter zip file name format where the article ID is a formal part of the name;
  - the `.docx` file name itself, inside the zip file, could have a specific name format which indicates the article ID
  - we could require that the zip file contains a manifest file or extra file that specified the article ID or base DOI value
  - the `.docx` file for a decision letter could include the article ID or the base DOI, such as: **DOI:** 10.7554/eLife.00666  (although this could lead to more typos)
   - each sub article in the `.docx` would have its own DOI specified, like **DOI: 10.7554/eLife.00666.DL for the decision letter (also could lead to typos)
- An assumption

---

## Tasks

- [ ] Decide on how the article ID will be specified in the file names or file contents
- [ ] A description

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes

@Melissa37 this is a minor detail but it offers some options for where the article ID or DOI is specified as part of a zip package. It would be good to make a final selection of how this is in order to move forward. 

The answer may already be in issue https://github.com/elifesciences/decision-letter-parser/issues/4 suggesting a file name like `12345.zip`. If so, that will make the decision here easy, and I can lay out the remaining steps to turn that into the DOI values.

**Comment by Melissa37** [comment]
>we establish a decision letter zip file name format where the article ID is a formal part of the name

Yes, this is done in #14 

>the .docx file name itself, inside the zip file, could have a specific name format which indicates the article ID

I think it makes sense for the file name to have a specific name format anyway. I would suggest no the same as the zip file naming

>we could require that the zip file contains a manifest file or extra file that specified the article ID or base DOI value

The editorial team produce this, it would be unfair to ask for a manifest file I think!

>the .docx file for a decision letter could include the article ID or the base DOI, such as: DOI: 10.7554/eLife.00666 (although this could lead to more typos)

I agree - too much text for a manual process and I'd say unnecessary

>each sub article in the .docx would have its own DOI specified, like **DOI: 10.7554/eLife.00666.DL for the decision letter (also could lead to typos)

I agree - too much text for a manual process and I'd say unnecessary

Additional point - extensibility. We might start producing more than one sub-article asset. I wonder whether there is any value in having a separate .dox file per sub article and naming it appropriately, eg 12345-DL and 12345-AR.
Then if we start publishing reviews as well, they could be 12345-R1, 12345-R2 etc.
This might make it easier?

@acollings do you have any thoughts on this?

**Comment by acollings** [comment]
Hi @Melissa37 what you've said sounds good. I agree regarding extensibility. Cheers, Andy

**Comment by gnott** [comment]
Discussed again starting in comment https://github.com/elifesciences/XML-mapping/issues/87#issuecomment-540811576, let's aim for setting `<sub-article>` DOI values that use the `@id` attribute value, e.g. 10.7554/eLife.42687.sa1

The DOI prefix will be specified in the `letterparser.cfg` file.
