### ISSUE TITLE
Reference parsing

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#3]
## Problem / Motivation

- WHO Editorial may include references in the decision letter
- WHEN and WHERE 
- WHAT References in the output can be simple, there is no need to tag or link them specially
- WHY Mentions of a reference may exist in a simple way in the copy

## Proposed solution

- Standard content conversion, should not require too much else

## Clarification needed and assumptions

Q. Similarly, what about linking of references in the copy? (I see in the
samples that they are maybe not linked anyway)
A. We do not convert references to links in the decision letter and response. Sometimes authors provide the references and a reference list in the author response. However, these should not be provided "citation" privileges and so do not make it to the reference list, cross ref etc.So best not to create any cross links, even to references in the list

---

## Tasks

- [x] Parse the content as written, no need for special tagging of references in the output
- [x] Could include a test case specifically illustrating it

## Technical notes
- Standard pandoc `.docx` content conversion

**Comment by Melissa37** [comment]
👍

**Comment by gnott** [comment]
From what I can see in early tests is any citation mentioned in the letter are just text. We are not enhancing them in any way. I don't see the need for a specific test case for these, since they are just like all the other text. Closing this issue!
