### ISSUE TITLE
xref tag linking to author response image, tables, video

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#31]
## Problem / Motivation

- WHO wants this? Production
- WHEN and WHERE do they want it? When a `.docx` file is converted to JATS XML, to surround mentions of an author reponse image in the text with an `<xref>` tag to the id of the fig
- WHAT do they want? e.g. "see `<xref ref-type="fig" rid="respfig1">`Author response image 1.`</xref>`"
- WHY do they want this? This makes for a more complete decision letter XML

## Proposed solution

- Possibly detect the mentions of author response images / table / video in the `.docx` file itself, but so far the output doesn't indicate any special highlighting or index references from files where sometimes they show a grey highlight on some text like this
- Alternatively, add the `<xref>` tags by matching a particular pattern of text. Some of them may be expressed like `(Author response image 1)` or `(see Author response image 1)`. This pattern matching may be difficult and sometimes faulty
- Additionally, the `@rid=` attribute of the `<xref>` tag needs to be set, and the `@id=` attribute of the element it will match is currently only added as the final step to finalising the JATS XML output. The `@rid` may need to be set or reset as one of the final stages of XML building.

## Clarification needed and assumptions

- A question is whether the text mentions in the `.docx` are in a predictable enough pattern that we can correctly add `<xref>` tags around these terms
- An assumption is the benefit of trying to do this outweighs the alternative which is not to add the `<xref>` tags

---

## Tasks

- [x] A description of a task
- [x] A description

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes

@Melissa37 some details and questions around automatically adding `<xref>` tags to fig, table, video assets.

**Comment by Melissa37** [comment]
@acollings Could we assume that any in-text citations of the figures/tables/videos in the author response will be formatted in this way: eg "Author response image 1"?

**Comment by acollings** [comment]
@Melissa37 @gnott yes, I think they should be predictable enough, e.g., with "Author response image/table/video 1" and "see Author response image/table/video 1" the most likely ways of referring to the assets. If we miss a few links because of unusual labelling, I'd say that's okay.

**Comment by Melissa37** [comment]
Thanks @acollings sounds good to me -  is that all the info you need @gnott ?

**Comment by gnott** [comment]
This is helpful and encouraging. We can plan to link these terms if they match the expected wording exactly, and if we miss some, it is no big loss.

**Comment by gnott** [comment]
In PR https://github.com/elifesciences/decision-letter-parser/pull/61 I have a working example of this logic.

Assets (fig, media (video), table-wrap) in the XML is generated from docx file data. The `<label>` for those is used as a possible term to match in paragraph text. If the term is found, it is surrounded with an appropriate `<xref>` tag for that asset.

When the PR is merged, I'll consider this issue completed. We may encounter bugs with certain data, which we'll discover when using this library more heavily.
