### ISSUE TITLE
Video parsing

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#46]
Similar to figure parsing https://github.com/elifesciences/decision-letter-parser/issues/2

- [x] Parse `.docx` video content
- [x] Format the data into a `<media>` tag into the JATS output
- [x] Specify video file naming format

**Comment by gnott** [comment]
I found one eLife example of a video in an author response in article `40497` and there is a sample `.docx` for the decision letter content. Other articles with videos in their author responses include `04953`, `09351`, and `07398` but I do not have original `.docx` files handy to look at for those.

In the `40497` `.docx` file the mention of the video is simply:

```
<Author response video 1>
```

It seems to have no particular title or caption.

I am going to follow a similar pattern as the figure content for how a title would be specified in the `.docx` file, wrapped by a `<Author response video 1 title/legend>` "tag" in the content.

**Comment by Melissa37** [comment]
Thanks @gnott 

@acollings do you have any comment on this - should videos in decision letter/author responses have some sort of caption?

@FAtherden-eLife @JGilbert-eLife For info/input

**Comment by FAtherden-eLife** [comment]
@gnott other samples (which you might have `.docx` files for) include:
- http://doi.org/10.7554/eLife.41540.032
- http://doi.org/10.7554/eLife.44816.037
- http://doi.org/10.7554/eLife.44816.038
- http://doi.org/10.7554/eLife.48932.047
- http://doi.org/10.7554/eLife.48932.050


There are only 10 of these in all our content, and it looks like 8 of them have some sort of legend (title or caption).

**Comment by acollings** [comment]
Hi all, I think it's better for videos in the Author Response to have a brief caption, but as we have a mix in the archive, what will happen if there isn't one? (Either way, the numbers are small, so I don't really mind.)

**Comment by gnott** [comment]
Thansk for mentioning the additional article examples @FAtherden-eLife - I knew I might be missing some, but I didn't realise my BaseX database was so out of date when I ran a quick query yesterday. I will check for some `.docx` files for the newer ones.

Videos seem to have only a label or a label and a title. It looks like it can follow similar logic to what is used for figures, where the first sentence can serve as the title, the rest as paragraphs in the caption.

I will create some code tests to handle if the title is omitted, however I may suggest in the `.docx` file going forward to always include a portion of text to be used as the label. That would keep things consistent logic-wise.

**Comment by gnott** [comment]
The `.docx` file for article `44816` is probably the most complete example and is in keeping with the suggested naming, a screenshot:

![image](https://user-images.githubusercontent.com/1779115/68060145-60d2f500-fcbc-11e9-9f85-4c21084bff77.png)

The `.docx` files for articles `48932` and `41540` are not ideal, because there's no reference to the video files at all in the copy, so there would be no indication of where to place the `<media>` tag in the final XML output.

I continue with a recommendation to always specify a `<Author response video 1>` style tag for the video placement, and to also at least include a value to be used in the `<label>` tag, e.g. `<Author response video 1 title/legend>Author response video 1.</Author response video 1 title/legend>`, where the **Author response video 1.** phrase is bold style.
