### ISSUE TITLE
Figure caption title example from eLife 39122

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#47]
Yesterday I made progress on ticket https://github.com/elifesciences/decision-letter-parser/issues/2, parsing the figure content from `.docx` data.

The test data example I'm using right now is based on eLife article `39122`. I described this on a call today with you @Melissa37.

The complication is trying to set a figure `<title>` value from the data available. I will include some XML snippets below to illustrate the challenge.

1. JATS produced by `pandoc` from the `.docx` file

The first three paragraphs look like this:

```
<p>&lt;Author response image 1&gt;</p>
<p>
&lt;Author response image 1 title/legend&gt;
<bold>Author response image 1.</bold>
Model calculations based on the energy profile of G644P at zero Ca
<sup>2+</sup>
(top) and a WT-like channel with a totally symmetric energy profile (bottom). Left, Ion occupancy in the model channel relative to that at the outermost wells (p
<sub>n</sub>
or p
<sub>0</sub>
) as a function of voltage at the indicated locations. Right, Shape of the I-V relation at steady state. At zero voltage, the relative occupancy is 1 for all cases because our model assumes no binding affinity when no voltage gradient is present. The curves on the left panels were calculated using
</p>
<p>
<disp-formula>
...
```

The final XML produced for this article (in `elife-39122-v2.xml`) looks like this:

```
<fig id="respfig1">
<object-id pub-id-type="doi">10.7554/eLife.39122.018</object-id>
<label>Author response image 1.</label>
<caption>
<title>
Model calculations based on the energy profile of G644P at zero Ca
<sup>2+</sup>
(top) and a WT-like channel with a totally symmetric energy profile (bottom).
</title>
<p>
Left, Ion occupancy in the model channel relative to that at the outermost wells (p
<sub>n</sub>
or p
<sub>0</sub>
) as a function of voltage at the indicated locations. Right, Shape of the I-V relation at steady state. At zero voltage, the relative occupancy is 1 for all cases because our model assumes no binding affinity when no voltage gradient is present. The curves on the left panels were calculated using
<disp-formula id="equ20">
...
```

As you may see in the snippets, in the final XML, the `<caption><title>` value and the first `<caption><p>` value are difficult to automatically create from the snippet produced by `pandoc`.

Part of this may be due to some editing and typesetting that happened between when the initial decision letter `.docx` file was produced and the final article XML was typeset.

My solution so far is to just duplicate the `<label>` into the `<caption><title>`, and then include all the caption content into the `<caption><p>` tag. This would look like:

```
<fig>
<label>Author response image 1.</label>
<caption>
<title>Author response image 1.</title>
<p>Model calculations based on the energy profile of G644P ...</p>
```

I don't know what steps we would take here. I wanted to describe the topic, including some examples, which may serve as points of discussion, or even just as documentation about how the content is being formatted in the final XML output produced by this code library.

Tasks:

- [x] Try using the first sentence up to the full stop as the `<title>` value

**Comment by gnott** [comment]
Also, it might be a good way to warm up to this if you view the figure on eLife journal at https://elifesciences.org/articles/39122#respfig1 and click the `"see more >>"` link to expand the caption.

**Comment by JGilbert-eLife** [comment]
Hi @gnott,

Wold it work to always take everything up to the first full stop in the title/legend paragraph as the title? That wouldn't be a perfect solution, but it would save on pushing more requirements to editorial. We've more or less been doing exactly that for years now, so if a few not-quite overall titles get included, it won't do any serious harm.

There is also the case where no title or legend will be provided at all, so that'll have to be accounted for as well.

Thanks,

James

**Comment by gnott** [comment]
Carving up the string into a title and caption is generally good. It might run into an exception on strange input but we can account for that when I have a failing example.
