### ISSUE TITLE
Editor names in decision letter

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#5]
## Problem / Motivation

- WHO Editorial may include editor names in plain text in `.docx` files
- WHEN and WHERE In `.docx` files will flow through to the JATS output
- WHAT Keep the editor names in plain text as written
- WHY Editor names may come from a different set of data and will be added by typesetters later after the rough decision letter is provided to them

## Proposed solution

- Parse the editor names, if present, like all the other content and include them as plain text

## Clarification needed and assumptions

- There is no need (at this time) to add editor names as tagged author JATS XML into the output of the decision letter parser
- Integrating the decision letter into another tool, like Texture, and how the editor names are specified is out of scope for the parser project at this time

---

## Tasks

- [x] Parse editor `.docx` content as written and requires no special logic 

## Technical notes
- pandoc and parsing logic as will be used for all other content

**Comment by Melissa37** [comment]
👍

**Comment by gnott** [comment]
Nothing to do! I will close this.

**Comment by gnott** [comment]
Hi @Melissa37, we raise this issue a while ago and closed it a while later. I think it might be in future we do want to add contributor names to the XML, do you agree? If so, I can create a fresh new isssue for it and it can be on the upcoming list until it we want to implement it.

**Comment by Melissa37** [comment]
Thanks @gnott I agree we'll probably want in the future and agree we can create a new issue when that happens.
