### ISSUE TITLE
Automated tests for decision-letter-parser library

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#6]
New library, I added really basic build scripts so far. When you have a moment to configure it on internal build infrastructure

- [x] Create a library build job
- [x] Add coverage token
- [x] ~~Future: will probably need `pandoc` executable installed - may not be required to install separately, this is done when installing `pypandoc` I think~~ - we can delay this for now, opting for Docker instead
- [x] Call pandoc via Docker

Third bullet is not yet a requirements for passing tests, but if `pypandoc` module works well (in first experiments it looks good) then it will require `pandoc` to be installed and in the `PATH` or set like `export PYPANDOC_PANDOC=[path to pandoc executable]`.

**Comment by giorgiosironi** [comment]
You know the drill:
https://github.com/kns-it/Docker-Pandoc
Would that solve your problem?

**Comment by giorgiosironi** [comment]
(it seems to have very recent versions, too, rather than being tied to the Linux distribution)

**Comment by giorgiosironi** [comment]
Added @elifesciences/butlers at https://github.com/elifesciences/decision-letter-parser/settings/collaboration

**Comment by giorgiosironi** [comment]
Added `decision-letter-parser` to the whitelist in https://alfred.elifesciences.org/job/pull-requests-projects/computation/console

**Comment by giorgiosironi** [comment]
Also added https://alfred.elifesciences.org/job/libraries/job/library-decision-letter-parser/ triggered from `develop`.

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/libraries/job/library-decision-letter-parser/1/console is green but contains some errors like:
```
11:28:31  ERROR: InvocationError: could not find executable 'coverage'
```
Also, shouldn't it remove Python 2.7?

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/pull-requests-projects/job/decision-letter-parser/view/change-requests/job/PR-7/ is green after adding the coverage token.

**Comment by gnott** [comment]
Green is good. Thanks @giorgiosironi ! I agree the Python 2.7 support may as well be dropped, since it will never need to be run in that version.

**Comment by gnott** [comment]
Based on the most recent test runs, I am unchecking the DoD box for `pandoc` installation. It looks to be not solved in the Ubuntu builds.

**Comment by gnott** [comment]
When `pandoc` is not available, it will attempt to call it via Docker. The recent tests are green, and I will go ahead and close this issue as completed. Thanks for the help @giorgiosironi!
