### ISSUE TITLE
Update pandoc version to > 2.7.0

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#68]
After investigating the bug in issue https://github.com/elifesciences/decision-letter-parser/issues/49, I found the minimum version of `pandoc` where the bug is fixed is `2.7.3`, based on the Docker hub releases:

https://hub.docker.com/r/pandoc/core/tags

There are more recent versions there too, in the `2.8` and `2.9` range.

Any opinions @lsh-0 or @giorgiosironi about choosing which version we want to deploy?

Would being exact, such as using version `2.9.1.1`, be the way to go, or instead use `2.9`.

Or, is `2.9` too new?

**Comment by lsh-0** [comment]
is this running within a container or on the instance itself?

if it's running on the instance itself, you're stuck with the version that comes with it. [18.04 uses 1.19](https://packages.ubuntu.com/bionic/pandoc)

if you're running it inside a container then it's up to you what version you install - you're responsible for the application building within the container and working correctly. 

is `decision-letter-parser` an elife-bot dependency or a sort-of standalone app?

**Comment by giorgiosironi** [comment]
No preference for me.

**Comment by gnott** [comment]
The `pandoc` call is containerised. Tests on the `elife-bot` project would depend on it functioning, but so far the tests are not so detailed as to care which specific verison of pandoc is used (I think). I don't see there being any security concerns about the `pandoc` version in how it is used.

I see in the release notes for `pandoc` version `2.9.1.1` there is a specific change to the JATS functionality (related to `<ext-link>` tags). I think I will aim to use that version and then we can adjust it as time goes along.
