### ISSUE TITLE
Decision letter boxed-text preamble XML

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#8]
Looking at some final decision letter XML, I notice the body starts with preamble such as this:

```
<boxed-text>
<p>
In the interests of transparency, eLife includes the editorial decision letter and accompanying author responses. A lightly edited version of the letter sent to the authors after peer review is shown, indicating the most substantive concerns; minor comments are not usually included.
</p>
</boxed-text>
```

It may be possible to add this to the output from this library, with the copy being specified in a configuration file.

@Melissa37 do you think including this preamble to the output that will be supplied to vendors is important, or can it be left out at this stage?

Todo

- [x] Boilerplate preamble to be specified in a configuration file, to be used as the default value
- [x] If a value is included in the `.docx` file for this preamble, then use that instead
- [x] Need to specify a format for how the preamble will look in a `.docx`, possibly at the very top with format like "**Preamble:** [preamble content following the recognisable title]"

**Comment by Melissa37** [comment]
@gnott This boxed texted content is subject to change, especially as we experiment with the peer review process so I prefer to give the editorial team the freedom to use the text they need to use when creating the decision letters without the need to inform systems to make changes, which might not always be tied to a specific article type. 

We could ask Editorial to "style" this boxed text content in some way so you can pick it out?

@acollings

**Comment by acollings** [comment]
Hi @gnott and @Melissa37: thanks for this. I'm sure we'd be happy to include the relevant text in the file we provide. With various changes planned, it would be nice to have the flexibility to change that sentence in a fairly easy way when we need to. As to how we present it to make it easy to parse, I'm open to suggestions!

**Comment by gnott** [comment]
I had not considered that we can change the `.docx` to include the particular statement, which I think may provide the flexibility here. If you do not have it in the `.docx`, then we can use a standard boilerplate value. I will add some todo checkboxes to the issue reflecting this plan, and please add more comments if I am off track.

**Comment by Melissa37** [comment]
Cool, thanks. This sounds like a great plan!
M

**Comment by gnott** [comment]
Before I start on this, it would be useful to gather comments about what this optional section should be called.

I think we can probably follow a similar format as the **Decision letter** and **Author response** sections in the `.docx` file example, that is like this (bold, on its own line):

![image](https://user-images.githubusercontent.com/1779115/62171162-e40e3480-b2e2-11e9-887c-67c8dcad62c7.png)

For the name of the section, some ideas to choose from: **Preamble**, **Preface**, **Editor's note**, or it could be something else (please suggest).

**Comment by Melissa37** [comment]
@acollings is away until mid-next week - are you OK with waiting for then for an answer as I feel he is best placed to name this :-)

In the future, I don't think we'll place this in `<boxed-text>`, but we'll see!

M

**Comment by gnott** [comment]
It can wait. There's lots more to do, and we can always change any value used for it, if I must proceed anyway.

**Comment by acollings** [comment]
Hi @gnott and @Melissa37 **Preamble** would work for this text. Thanks!

**Comment by gnott** [comment]
Thanks for the answers! Now I'm back to actively developing this parsing library, I will assign this issue to myself and I will be starting on it.

**Comment by gnott** [comment]
The default value for the preamble is added into the `config` branch that is under development. That logic will eventually be merged and is part of issue https://github.com/elifesciences/decision-letter-parser/issues/43, so I will close this particular issue as completed.
