### ISSUE TITLE
Maths alternatives

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#9]
I am reviewing the raw JATS output from pandoc now. Specifically regarding maths equations, it is providing some `<alternatives>`, e.g.

```
<p>
  <disp-formula>
    <alternatives>
      <tex-math><![CDATA[I = zFJ]]></tex-math>
      <mml:math display="block" xmlns:mml="http://www.w3.org/1998/Math/MathML">                    
        <mml:mrow>
          <mml:mi>I</mml:mi>
          <mml:mo>=</mml:mo>
          <mml:mi>z</mml:mi>
          <mml:mi>F</mml:mi>
          <mml:mi>J</mml:mi>
        </mml:mrow>
      </mml:math>
    </alternatives>
  </disp-formula>
</p>
```

My assumption right now is we would prefer to use the mathml version of formulae in the output we send to the vendor. I cannot remember whether tex math would be preferred in the future.

@Melissa37 for the output of this library for eLife's purposes, would it be advantageous to use the JATS output as above, which includes the `<alternatives>`, or is it better to just select one of these alternatives for the final output?

It is also possible using one, the other, or both could be specified in a configuration file so it can produce different output depending on changing preferences in the future.

**Comment by Melissa37** [comment]
>My assumption right now is we would prefer to use the mathml version of formulae in the output we send to the vendor. I cannot remember whether tex math would be preferred in the future.

That is correct. The change to TexMath will be with Texture, so not going to happen any time soon!

>@Melissa37 for the output of this library for eLife's purposes, would it be advantageous to use the JATS output as above, which includes the <alternatives>, or is it better to just select one of these alternatives for the final output?

I defer to those with much greater knowledge on this! @FAtherden-eLife or @JGilbert-eLife WDYT? Or is this something we need to ask Exeter via https://gitlab.com/ExeterPremedia/Customers/eLife-1.5/issues/285 ?

**Comment by JGilbert-eLife** [comment]
I'm pretty sure that for us, it would be best to keep it simple and just use one of the options - `tex-math` when we have it up and running.

**Comment by gnott** [comment]
Thanks for the input! This issue is actionable now, I will self-assign it.

**Comment by gnott** [comment]
Simplification of the math formulas is working now on the current `build` branch code. I'll close this for now as completed.
